baseURL = "https://x7peeps.com/"
title = "x7peeps"
defaultContentLanguage = "zh"
locale = "zh-CN"
hasCJKLanguage = true
disablePathToLower = true
preserveTaxonomyNames = true
enableRobotsTXT = true
enableGitInfo = true

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe = true
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.extensions]
      mark = true

[module]
[[module.imports]]
path = "github.com/McShelby/hugo-theme-relearn"

[params]
ordersectionsby = "weight"
alwaysopen = false
collapsibleMenu = true
showVisitedLinks = true
disableLandingPageButton = true
disableShortcutsTitle = true
themeVariant = "relearn-dark"
hideAuthorDate = false

[frontmatter]
date = ["date", ":fileModTime", ":default"]
lastmod = [":git", "lastmod", "date", ":fileModTime", ":default"]

hideAuthorName = true
hideAuthorEmail = true

[params.math]
disable = true

[params.mermaid]
disable = true

[params.openapi]
disable = true

[params.author]
name = "x7peeps"

[languages]
  [languages.zh]
  title = "x7peeps"
  weight = 1
  label = "中文"

[params.search]
disable = true

  [params.search.index]
  disable = true

  [params.search.page]
  disable = true

[params.x7]
constellationDesktopParticles = 120
constellationMobileParticles = 40
enableConstellation = true
enableReadingDensity = true

[minify]
  disableHTML = false
  disableCSS = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true

[outputFormats.X7Search]
  baseName = "search"
  mediaType = "application/json"
  isPlainText = true
  isHTML = false
  noUgly = true

[outputs]
  home = ["html", "json", "X7Search"]

[markup.tableOfContents]
  endLevel = 4
  ordered = false
  startLevel = 2
